### ISSUE TITLE
XTea on PyPi seems to have not been updated

### ISSUE THREAD

**Issue by timgates42** [Varbin/xtea#10]
Is this the right PyPi package location - https://pypi.org/project/xtea/ the version on it seems much older than the version in use on GitHub and it lacks some of the recent fixes. Is it possible to publish an update?

**Comment by Varbin** [comment]
Thank you for the reminder.

 I've completely forgotten to update this package on PyPi. You can expect a new release in the next few days or even hours.

**Comment by timgates42** [comment]
Thanks @Varbin can see it was released an hour ago.
